package Model;
// Generated Dec 19, 2017 12:33:05 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gift generated by hbm2java
 */
@Entity
@Table(name="Gift"
    ,schema="dbo"
    ,catalog="HoDan"
)
public class Gift  implements java.io.Serializable {


     private Long quaid;
     private String qua;
     private Integer dien;
     private Integer sluong;

    public Gift() {
    }

	
    public Gift(Long quaid, String qua) {
        this.quaid = quaid;
        this.qua = qua;
    }
    public Gift(Long quaid, String qua, Integer dien, Integer sluong) {
       this.quaid = quaid;
       this.qua = qua;
       this.dien = dien;
       this.sluong = sluong;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="Quaid", unique=true)
    public Long getQuaid() {
        return this.quaid;
    }
    
    public void setQuaid(Long quaid) {
        this.quaid = quaid;
    }

    
    @Column(name="Qua", nullable=false, length=50)
    public String getQua() {
        return this.qua;
    }
    
    public void setQua(String qua) {
        this.qua = qua;
    }

    
    @Column(name="Dien")
    public Integer getDien() {
        return this.dien;
    }
    
    public void setDien(Integer dien) {
        this.dien = dien;
    }

    
    @Column(name="SLuong")
    public Integer getSluong() {
        return this.sluong;
    }
    
    public void setSluong(Integer sluong) {
        this.sluong = sluong;
    }




}


