package Model;
// Generated Dec 18, 2017 2:07:07 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gift generated by hbm2java
 */
@Entity
@Table(name="Gift"
    ,schema="dbo"
    ,catalog="HoDan"
)
public class Gift  implements java.io.Serializable {


     private long quaId;
     private Serializable qua;
     private Integer dien;
     private Integer sluong;

    public Gift() {
    }

	
    public Gift(long quaId, Serializable qua) {
        this.quaId = quaId;
        this.qua = qua;
    }
    public Gift(long quaId, Serializable qua, Integer dien, Integer sluong) {
       this.quaId = quaId;
       this.qua = qua;
       this.dien = dien;
       this.sluong = sluong;
    }
   
     @Id 

    
    @Column(name="QuaId", unique=true, nullable=false)
    public long getQuaId() {
        return this.quaId;
    }
    
    public void setQuaId(long quaId) {
        this.quaId = quaId;
    }

    
    @Column(name="Qua", nullable=false)
    public Serializable getQua() {
        return this.qua;
    }
    
    public void setQua(Serializable qua) {
        this.qua = qua;
    }

    
    @Column(name="Dien")
    public Integer getDien() {
        return this.dien;
    }
    
    public void setDien(Integer dien) {
        this.dien = dien;
    }

    
    @Column(name="SLuong")
    public Integer getSluong() {
        return this.sluong;
    }
    
    public void setSluong(Integer sluong) {
        this.sluong = sluong;
    }




}


