package Model;
// Generated Dec 19, 2017 12:33:05 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name="Personal"
    ,schema="dbo"
    ,catalog="HoDan"
)
public class Personal  implements java.io.Serializable {


     private long identityCode;
     private House house;
     private String name;
     private Integer age;
     private Integer birthYear;
     private String career;
     private Integer dienDacBiet;

    public Personal() {
    }

	
    public Personal(long identityCode, House house, String name) {
        this.identityCode = identityCode;
        this.house = house;
        this.name = name;
    }
    public Personal(long identityCode, House house, String name, Integer age, Integer birthYear, String career, Integer dienDacBiet) {
       this.identityCode = identityCode;
       this.house = house;
       this.name = name;
       this.age = age;
       this.birthYear = birthYear;
       this.career = career;
       this.dienDacBiet = dienDacBiet;
    }
   
     @Id 

    
    @Column(name="IdentityCode", unique=true, nullable=false)
    public long getIdentityCode() {
        return this.identityCode;
    }
    
    public void setIdentityCode(long identityCode) {
        this.identityCode = identityCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="HouseId", nullable=false)
    public House getHouse() {
        return this.house;
    }
    
    public void setHouse(House house) {
        this.house = house;
    }

    
    @Column(name="Name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Age")
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }

    
    @Column(name="BirthYear")
    public Integer getBirthYear() {
        return this.birthYear;
    }
    
    public void setBirthYear(Integer birthYear) {
        this.birthYear = birthYear;
    }

    
    @Column(name="Career", length=20)
    public String getCareer() {
        return this.career;
    }
    
    public void setCareer(String career) {
        this.career = career;
    }

    
    @Column(name="dienDacBiet")
    public Integer getDienDacBiet() {
        return this.dienDacBiet;
    }
    
    public void setDienDacBiet(Integer dienDacBiet) {
        this.dienDacBiet = dienDacBiet;
    }




}


