package Model;
// Generated Dec 19, 2017 6:21:36 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Phi generated by hbm2java
 */
@Entity
@Table(name="Phi"
    ,schema="dbo"
    ,catalog="HoDan"
)
public class Phi  implements java.io.Serializable {


     private String houseId;
     private House house;
     private boolean phiXdCsht;
     private boolean phiTuThien;
     private boolean quyQuocPhong;
     private boolean phiDuyTriPhuong;
     private boolean quyKhuyenHoc;
     private boolean quyCsNgCaoTuoi;

    public Phi() {
    }

    public Phi(House house, boolean phiXdCsht, boolean phiTuThien, boolean quyQuocPhong, boolean phiDuyTriPhuong, boolean quyKhuyenHoc, boolean quyCsNgCaoTuoi) {
       this.house = house;
       this.phiXdCsht = phiXdCsht;
       this.phiTuThien = phiTuThien;
       this.quyQuocPhong = quyQuocPhong;
       this.phiDuyTriPhuong = phiDuyTriPhuong;
       this.quyKhuyenHoc = quyKhuyenHoc;
       this.quyCsNgCaoTuoi = quyCsNgCaoTuoi;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="house"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="HouseId", unique=true, nullable=false, length=10)
    public String getHouseId() {
        return this.houseId;
    }
    
    public void setHouseId(String houseId) {
        this.houseId = houseId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public House getHouse() {
        return this.house;
    }
    
    public void setHouse(House house) {
        this.house = house;
    }

    
    @Column(name="PhiXdCsht", nullable=false)
    public boolean isPhiXdCsht() {
        return this.phiXdCsht;
    }
    
    public void setPhiXdCsht(boolean phiXdCsht) {
        this.phiXdCsht = phiXdCsht;
    }

    
    @Column(name="PhiTuThien", nullable=false)
    public boolean isPhiTuThien() {
        return this.phiTuThien;
    }
    
    public void setPhiTuThien(boolean phiTuThien) {
        this.phiTuThien = phiTuThien;
    }

    
    @Column(name="QuyQuocPhong", nullable=false)
    public boolean isQuyQuocPhong() {
        return this.quyQuocPhong;
    }
    
    public void setQuyQuocPhong(boolean quyQuocPhong) {
        this.quyQuocPhong = quyQuocPhong;
    }

    
    @Column(name="PhiDuyTriPhuong", nullable=false)
    public boolean isPhiDuyTriPhuong() {
        return this.phiDuyTriPhuong;
    }
    
    public void setPhiDuyTriPhuong(boolean phiDuyTriPhuong) {
        this.phiDuyTriPhuong = phiDuyTriPhuong;
    }

    
    @Column(name="QuyKhuyenHoc", nullable=false)
    public boolean isQuyKhuyenHoc() {
        return this.quyKhuyenHoc;
    }
    
    public void setQuyKhuyenHoc(boolean quyKhuyenHoc) {
        this.quyKhuyenHoc = quyKhuyenHoc;
    }

    
    @Column(name="QuyCsNgCaoTuoi", nullable=false)
    public boolean isQuyCsNgCaoTuoi() {
        return this.quyCsNgCaoTuoi;
    }
    
    public void setQuyCsNgCaoTuoi(boolean quyCsNgCaoTuoi) {
        this.quyCsNgCaoTuoi = quyCsNgCaoTuoi;
    }




}


