/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author procc
 */
public class Design extends javax.swing.JFrame {

    JInternalFrame form = new JInternalFrame();
    public Design() {
        initComponents();
        setLocationRelativeTo(null);
        jPanelSo6.hide();
        jPanelSo4.hide();
        jPanelSo5.hide();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelHoDan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelHoDan = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelQua = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelQua = new javax.swing.JLabel();
        jPanelDs = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelDs = new javax.swing.JLabel();
        jPanelQuy = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabelQuy = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelSo3 = new javax.swing.JPanel();
        jLabelSo3 = new javax.swing.JLabel();
        jPanelSo1 = new javax.swing.JPanel();
        jLabelSo1 = new javax.swing.JLabel();
        jPanelSo2 = new javax.swing.JPanel();
        jLabelSo2 = new javax.swing.JLabel();
        jPanelSo4 = new javax.swing.JPanel();
        jLabelSo4 = new javax.swing.JLabel();
        jPanelSo5 = new javax.swing.JPanel();
        jLabelSo5 = new javax.swing.JLabel();
        jPanelSo6 = new javax.swing.JPanel();
        jLabelSo6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanelLamViec = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1316, 630));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1319, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHoDan.setBackground(new java.awt.Color(204, 204, 255));
        jPanelHoDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHoDanMousePressed(evt);
            }
        });
        jPanelHoDan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Home_15px.png"))); // NOI18N
        jPanelHoDan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 0, 31, 47));

        jLabelHoDan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHoDan.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoDan.setText("Hộ dân");
        jPanelHoDan.add(jLabelHoDan, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 11, -1, -1));

        jPanel1.add(jPanelHoDan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 320, 50));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel3);
        jLabel3.setBounds(22, 0, 31, 47);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel2");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(71, 11, 48, 20);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 320, -1));

        jPanelQua.setBackground(new java.awt.Color(204, 204, 255));
        jPanelQua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelQuaMousePressed(evt);
            }
        });
        jPanelQua.setLayout(null);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Gift_15px.png"))); // NOI18N
        jPanelQua.add(jLabel7);
        jLabel7.setBounds(22, 0, 31, 47);

        jLabelQua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelQua.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQua.setText("Danh sách quà");
        jPanelQua.add(jLabelQua);
        jLabelQua.setBounds(71, 11, 190, 20);

        jPanel1.add(jPanelQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 320, 50));

        jPanelDs.setBackground(new java.awt.Color(204, 204, 255));
        jPanelDs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelDsMousePressed(evt);
            }
        });
        jPanelDs.setLayout(null);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_List_of_Thumbnails_15px.png"))); // NOI18N
        jPanelDs.add(jLabel9);
        jLabel9.setBounds(22, 0, 31, 47);

        jLabelDs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDs.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDs.setText("Danh sách");
        jPanelDs.add(jLabelDs);
        jLabelDs.setBounds(71, 11, 110, 20);

        jPanel1.add(jPanelDs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 320, 50));

        jPanelQuy.setBackground(new java.awt.Color(204, 204, 255));
        jPanelQuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelQuyMousePressed(evt);
            }
        });
        jPanelQuy.setLayout(null);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Payroll_15px.png"))); // NOI18N
        jPanelQuy.add(jLabel8);
        jLabel8.setBounds(22, 0, 31, 47);

        jLabelQuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelQuy.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuy.setText("Quỹ");
        jPanelQuy.add(jLabelQuy);
        jLabelQuy.setBounds(71, 11, 27, 20);

        jPanel1.add(jPanelQuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 320, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 700));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hộ dân");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 38, 191, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hộ dân");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 64, 191, -1));

        jPanelSo3.setBackground(new java.awt.Color(153, 153, 255));
        jPanelSo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSo3MousePressed(evt);
            }
        });
        jPanelSo3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSo3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSo3.setText("Thêm người");
        jPanelSo3.add(jLabelSo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel2.add(jPanelSo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 160, 30));

        jPanelSo1.setBackground(new java.awt.Color(153, 153, 255));
        jPanelSo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSo1MousePressed(evt);
            }
        });
        jPanelSo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSo1.setText("Danh sách Hộ dân");
        jPanelSo1.add(jLabelSo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel2.add(jPanelSo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 30));

        jPanelSo2.setBackground(new java.awt.Color(153, 153, 255));
        jPanelSo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSo2MousePressed(evt);
            }
        });
        jPanelSo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSo2.setText("Danh sách cá nhân");
        jPanelSo2.add(jLabelSo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel2.add(jPanelSo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, 30));

        jPanelSo4.setBackground(new java.awt.Color(153, 153, 255));
        jPanelSo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSo4MousePressed(evt);
            }
        });
        jPanelSo4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSo4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSo4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSo4.setText("Thêm người");
        jPanelSo4.add(jLabelSo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel2.add(jPanelSo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 160, 30));

        jPanelSo5.setBackground(new java.awt.Color(153, 153, 255));
        jPanelSo5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSo5MousePressed(evt);
            }
        });
        jPanelSo5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSo5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSo5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSo5.setText("Thêm người");
        jPanelSo5.add(jLabelSo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel2.add(jPanelSo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 160, 30));

        jPanelSo6.setBackground(new java.awt.Color(153, 153, 255));
        jPanelSo6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSo6MousePressed(evt);
            }
        });
        jPanelSo6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSo6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSo6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSo6.setText("Thêm người");
        jPanelSo6.add(jLabelSo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel2.add(jPanelSo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 1000, 140));

        jLabel13.setBackground(new java.awt.Color(102, 204, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 204, 255));
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 20, -1));

        jPanelLamViec.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanelLamViecLayout = new javax.swing.GroupLayout(jPanelLamViec);
        jPanelLamViec.setLayout(jPanelLamViecLayout);
        jPanelLamViecLayout.setHorizontalGroup(
            jPanelLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanelLamViecLayout.setVerticalGroup(
            jPanelLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLamViec, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 1000, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelHoDanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHoDanMousePressed
        setColor(jPanelHoDan);
        resetColor(jPanelQua);
        resetColor(jPanelDs);
        resetColor(jPanelQuy);
        jPanelSo3.show();
        jPanelSo2.show();
        resetColorPanel(jPanelSo1);
        resetColorPanel(jPanelSo2);
        resetColorPanel(jPanelSo3);
        
        jLabel12.setText(jLabelHoDan.getText());
        jLabel11.setText(jLabelHoDan.getText());
        jLabelSo1.setText("Danh sách hộ dân");
        jLabelSo2.setText("Danh sách cá nhân");
        jLabelSo3.setText("Thêm người");
        jPanelSo6.hide();
        jPanelSo4.hide();
        jPanelSo5.hide();
    }//GEN-LAST:event_jPanelHoDanMousePressed

    private void jPanelQuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQuaMousePressed
        setColor(jPanelQua);
        resetColor(jPanelHoDan);
        resetColor(jPanelQuy);
        resetColor(jPanelDs);
        jPanelSo3.show();
        jPanelSo2.show();
        jPanelSo4.show();
        jPanelSo5.show();
        resetColorPanel(jPanelSo1);
        resetColorPanel(jPanelSo2);
        resetColorPanel(jPanelSo3);
        resetColorPanel(jPanelSo4);
        resetColorPanel(jPanelSo5);
         jLabel12.setText(jLabelQua.getText());
         jLabel11.setText(jLabelQua.getText());
        
        
        jLabelSo1.setText("Trung Thu");
        jLabelSo2.setText("Tết thiếu nhi");
        jLabelSo3.setText("Học sinh giỏi");
        jLabelSo4.setText("Thương bệnh binh");
        jLabelSo5.setText("Người khuyết tật");
        
        
    }//GEN-LAST:event_jPanelQuaMousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel13MousePressed

    private void jPanelDsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDsMousePressed
        setColor(jPanelDs);
        resetColor(jPanelHoDan);
        resetColor(jPanelQuy);
        resetColor(jPanelQua);
        resetColorPanel(jPanelSo1);
        resetColorPanel(jPanelSo2);
        resetColorPanel(jPanelSo3);
        resetColorPanel(jPanelSo4);
        resetColorPanel(jPanelSo5);
        jPanelSo3.show();
        jPanelSo2.show();
        jLabel12.setText(jLabelDs.getText());
        jLabel11.setText(jLabelDs.getText());
        
        jLabelSo1.setText("Nghĩa vụ quân sự");
        jLabelSo2.setText("Dân quân");
        jLabelSo3.setText("Danh sách thiếu nhi");
        
        jPanelSo6.hide();
        jPanelSo4.hide();
        jPanelSo5.hide();
    }//GEN-LAST:event_jPanelDsMousePressed

    private void jPanelSo3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSo3MousePressed
        setColor(jPanelSo3);
        resetColorPanel(jPanelSo2);
        resetColorPanel(jPanelSo1);
        if(jLabel11.getText().equals(jLabelHoDan.getText())){
            if(form != null) form.dispose();
        form = new JInternalFrameThemDanhSach();
        ((BasicInternalFrameUI)form.getUI()).setNorthPane(null);
        form.setVisible(true);
        jPanelLamViec.add(form);
        form.addInternalFrameListener(new InternalFrameAdapter() {
                public void internalFrameClosing(InternalFrameEvent e) {
                    
                }

            });
        }
        else if(jLabel11.getText().equals(jLabelDs.getText())){
            if(form != null) form.dispose();
        form = new JInternalFrameTreEm();
        ((BasicInternalFrameUI)form.getUI()).setNorthPane(null);
        form.setVisible(true);
        jPanelLamViec.add(form);
        form.addInternalFrameListener(new InternalFrameAdapter() {
                public void internalFrameClosing(InternalFrameEvent e) {
                  
                }

            });
        }
        else{
            if(form != null) form.dispose();
            form = new JInternalFrameHsg();
            ((BasicInternalFrameUI)form.getUI()).setNorthPane(null);
            form.setVisible(true);
            jPanelLamViec.add(form);
            form.addInternalFrameListener(new InternalFrameAdapter() {
                public void internalFrameClosing(InternalFrameEvent e) {
                  
                }

            });
        }
    }//GEN-LAST:event_jPanelSo3MousePressed

    private void jPanelSo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSo1MousePressed
        setColor(jPanelSo1);
        resetColorPanel(jPanelSo2);
        resetColorPanel(jPanelSo3);
        
        if(jLabel11.getText().equals(jLabelHoDan.getText())){
        if(form != null) form.dispose();
        form = new JInternalFrameThemHoDan();
        ((BasicInternalFrameUI)form.getUI()).setNorthPane(null);
        form.setVisible(true);
        jPanelLamViec.add(form);
        form.addInternalFrameListener(new InternalFrameAdapter() {
                public void internalFrameClosing(InternalFrameEvent e) {
                  
                }

            });
        }
        else if(jLabel11.getText().equals(jLabelDs.getText())){
        if(form != null) form.dispose();
        form = new JInternalFrameNghiaVu();
        ((BasicInternalFrameUI)form.getUI()).setNorthPane(null);
        form.setVisible(true);
        jPanelLamViec.add(form);
        form.addInternalFrameListener(new InternalFrameAdapter() {
                public void internalFrameClosing(InternalFrameEvent e) {
                  
                }

            });
        }
        else if(jLabel11.getText().equals(jLabelQuy.getText())){
            if(form != null) form.dispose();
            form = new JInternalFrameDongTien();
            ((BasicInternalFrameUI)form.getUI()).setNorthPane(null);
        form.setVisible(true);
        jPanelLamViec.add(form);
        form.addInternalFrameListener(new InternalFrameAdapter() {
                public void internalFrameClosing(InternalFrameEvent e) {
                  
                }

            });
        }
        else{
            if(form != null) form.dispose();
            form = new JInternalFrameTrungThu(); 
            ((BasicInternalFrameUI)form.getUI()).setNorthPane(null);
            form.setVisible(true);
            jPanelLamViec.add(form);
            form.addInternalFrameListener(new InternalFrameAdapter() {
                public void internalFrameClosing(InternalFrameEvent e) {
                  
                }

            });
        }
    }//GEN-LAST:event_jPanelSo1MousePressed

    private void jPanelSo2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSo2MousePressed
        setColor(jPanelSo2);
        resetColorPanel(jPanelSo1);
        resetColorPanel(jPanelSo3);
        if(jLabel11.getText().equals(jLabelHoDan.getText())){
        if(form != null) form.dispose();
        form = new JInternalFrameList();
        ((BasicInternalFrameUI)form.getUI()).setNorthPane(null);
        form.setVisible(true);
        jPanelLamViec.add(form);
        form.addInternalFrameListener(new InternalFrameAdapter() {
                public void internalFrameClosing(InternalFrameEvent e) {
                    
                }

            });
        }
        else if(jLabel11.getText().equals(jLabelDs.getText())){
            if(form != null) form.dispose();
            form = new JInternalFrameDanQuan();
            ((BasicInternalFrameUI)form.getUI()).setNorthPane(null);
        form.setVisible(true);
        jPanelLamViec.add(form);
        form.addInternalFrameListener(new InternalFrameAdapter() {
                public void internalFrameClosing(InternalFrameEvent e) {
                  
                }

            });
        }
        else{
            if(form != null) form.dispose();
            form = new JInternalFrameTetThieuNhi();
            ((BasicInternalFrameUI)form.getUI()).setNorthPane(null);
            form.setVisible(true);
            jPanelLamViec.add(form);
            form.addInternalFrameListener(new InternalFrameAdapter() {
                public void internalFrameClosing(InternalFrameEvent e) {
                  
                }

            });
        }
    }//GEN-LAST:event_jPanelSo2MousePressed

    private void jPanelSo6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSo6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelSo6MousePressed

    private void jPanelSo4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSo4MousePressed
       setColor(jPanelSo4);
        resetColorPanel(jPanelSo1);
        resetColorPanel(jPanelSo2);
        resetColorPanel(jPanelSo3);
        resetColorPanel(jPanelSo5);
            if(form != null) form.dispose();
            form = new JInternalFrameQuaDien1();
            ((BasicInternalFrameUI)form.getUI()).setNorthPane(null);
            form.setVisible(true);
            jPanelLamViec.add(form);
            form.addInternalFrameListener(new InternalFrameAdapter() {
                public void internalFrameClosing(InternalFrameEvent e) {
                  
                }

            });
    }//GEN-LAST:event_jPanelSo4MousePressed

    private void jPanelSo5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSo5MousePressed
        setColor(jPanelSo5);
        resetColorPanel(jPanelSo1);
        resetColorPanel(jPanelSo2);
        resetColorPanel(jPanelSo3);
        resetColorPanel(jPanelSo4);
            if(form != null) form.dispose();
            form = new JInternalFrameQuaDien2();
            ((BasicInternalFrameUI)form.getUI()).setNorthPane(null);
            form.setVisible(true);
            jPanelLamViec.add(form);
            form.addInternalFrameListener(new InternalFrameAdapter() {
                public void internalFrameClosing(InternalFrameEvent e) {
                  
                }

            });
    }//GEN-LAST:event_jPanelSo5MousePressed

    private void jPanelQuyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQuyMousePressed
        setColor(jPanelQuy);
        resetColor(jPanelHoDan);
        resetColor(jPanelDs);
        resetColor(jPanelQua);
        jLabel12.setText(jLabelQuy.getText());
        jLabel11.setText(jLabelQuy.getText());
        
        jLabelSo1.setText("Danh sách đóng tiền");
        
        
        jPanelSo6.hide();
        jPanelSo4.hide();
        jPanelSo3.hide();
        jPanelSo2.hide();
        jPanelSo5.hide();
    }//GEN-LAST:event_jPanelQuyMousePressed

    public void setColor(JPanel panel){
        panel.setBackground(new Color(102,102,255));
    }
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(204,204,255));
    }
    public void resetColorPanel(JPanel panel){
        panel.setBackground(new Color(153,153,255));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Design().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDs;
    private javax.swing.JLabel jLabelHoDan;
    private javax.swing.JLabel jLabelQua;
    private javax.swing.JLabel jLabelQuy;
    private javax.swing.JLabel jLabelSo1;
    private javax.swing.JLabel jLabelSo2;
    private javax.swing.JLabel jLabelSo3;
    private javax.swing.JLabel jLabelSo4;
    private javax.swing.JLabel jLabelSo5;
    private javax.swing.JLabel jLabelSo6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDs;
    private javax.swing.JPanel jPanelHoDan;
    private javax.swing.JPanel jPanelLamViec;
    private javax.swing.JPanel jPanelQua;
    private javax.swing.JPanel jPanelQuy;
    private javax.swing.JPanel jPanelSo1;
    private javax.swing.JPanel jPanelSo2;
    private javax.swing.JPanel jPanelSo3;
    private javax.swing.JPanel jPanelSo4;
    private javax.swing.JPanel jPanelSo5;
    private javax.swing.JPanel jPanelSo6;
    // End of variables declaration//GEN-END:variables
}
